-- liquibase formatted sql

-- changeset ramoni73:V3__background_data_background
INSERT INTO background(code, name, description, equipment, instruments, feat_id) VALUES
('Entertainer', 'Артист', 'Вы провели большую часть своей юности, следуя за передвижными ярмарками и карнавалами, подрабатывая музыкантом и акробатом в обмен на уроки. Возможно, вы научились ходить по канату, играть на лютне в особом стиле или декламировать поэзию с безупречной дикцией. По сей день вы наслаждаетесь аплодисментами и жаждете блистать на сцене.','Выберите А или Б: А) Музыкальный инструмент (тот, что вы выбрали выше), 2 костюма, стальное зеркало, духи, одежда путешественника, 11 зм; Б) 50 зм.','1 музыкальный инструмент на ваш выбор', (SELECT id FROM feat WHERE code = 'Musician')),
('Noble', 'Благородный', 'Вы были воспитаны в замке, окружённые богатством, властью и привилегиями. Ваша семья состоит из мелких аристократов, которые позаботились о том, чтобы вы получили первоклассное образование, часть которого вы ценили, а часть ненавидели. Время в замке, которое вы провели, наблюдая за своей семьёй при дворе, многому научило вас в вопросах лидерства.','Выберите А или Б: А) Парадная одежда, игровой набор (тот, что был выбран выше), духи, 29 зм; Б) 50 зм.','1 игровой набор на ваш выбор', (SELECT id FROM feat WHERE code = 'Skilled')),
('Sailor', 'Моряк', 'Вы жили мореплаванием, ветер дул вам в спину, а палубы качались у вас под ногами. Вы сидели на барных стульях в портах, которых уже и не вспомнить, пережили могучие штормы и обменивались историями с теми, кто живёт под водой.','Выберите А или Б: А) Кинжал, инструменты навигатора, верёвка, одежда путешественника, 20 зм; Б) 50 зм.','Инструменты навигатора', (SELECT id FROM feat WHERE code = 'Tavern_Brawler')),
('Sage', 'Мудрец', 'Вы провели годы своего становления, путешествуя между поместьями и монастырями, выполняя различные случайные работы и услуги в обмен на доступ к их библиотекам. Вы провели много долгих вечеров, уткнувшись носом в книги и свитки, изучая знания о мультивселенной (даже основы магии), и ваш разум жаждет большего.','Выберите А или Б: А) Боевой посох, книга (история), инструменты каллиграфа, роба, пергамент (8 листов), 8 зм; Б) 50 зм.','Инструменты каллиграфа', (SELECT id FROM feat WHERE code = 'Magic_Initiate')),
('Hermit', 'Отшельник', 'Вы провели свои ранние годы в уединении в хижине или монастыре, расположенном далеко за окраиной ближайшего поселения. В те дни вашими единственными компаньонами были лесные существа, и те, кто время от времени приходил с новостями из внешнего мира и припасами. Тишина и уединение позволяли вам проводить много часов, размышляя о тайнах мироздания.','Выберите А или Б: А) Боевой посох, спальник, лампа, масло (3 фляги), книга (философия), одежда путешественника, набор травника, 16 зм; Б) 50 зм.','Набор травника', (SELECT id FROM feat WHERE code = 'Healer')),
('Scribe', 'Писарь', 'Вы провели годы взросления в скриптории, монастыре, посвящённом сохранению знаний, или в правительственном учреждении, где научились писать чётким почерком и создавать изящные тексты. Возможно, вы писали правительственные документы или переписывали тома литературы. Возможно, вы умеете писать стихи, рассказы или проводить научные исследования. В первую очередь вы внимательны к деталям, что помогает вам не допускать ошибок в копируемых и создаваемых документах.','Выберите А или Б: А) Инструменты каллиграфа, парадная одежда, лампа, масло (3 фляги), пергамент (12 листов), 23 зм; Б) 50 зм.','Инструменты каллиграфа', (SELECT id FROM feat WHERE code = 'Skilled')),
('Acolyte', 'Послушник', 'Вы посвятили себя служению в городском храме или в уединённой священной роще. Там вы совершали священные обряды в честь бога или пантеона. Вы служили у священника и изучали религию. Благодаря наставлениям вашего священника и вашей собственной преданности вы также научились направлять толику божественной силы на служение вашему месту поклонения и людям, которые там молились.','Выберите А или Б: А) Инструменты каллиграфа, книга (молитвенник), священный символ, пергамент (10 листов), роба, 8 зм; Б) 50 зм.','Инструменты каллиграфа', (SELECT id FROM feat WHERE code = 'Magic_Initiate')),
('Criminal', 'Преступник', 'Вы научились зарабатывать деньги в тёмных переулках, подрезая кошельки или грабя магазины. Возможно, вы были частью небольшой банды преступников, которые присматривали друг за другом. Или, может быть, вы были одиноким волком, защищающимся от местной гильдии воров и более старых и грозных преступников.','Выберите А или Б: А) 2 кинжала, воровские инструменты, лом, 2 сумки, одежда путешественника, 16 зм; Б) 50 зм.','Воровские инструменты', (SELECT id FROM feat WHERE code = 'Alert')),
('Guide', 'Путешественник', 'Вы достигли совершеннолетия на открытом воздухе, вдали от заселённых земель. Ваш дом везде, где вы решили развернуть свой спальник. В дикой местности столько чудес (странные монстры, нетронутые леса и ручьи, заросшие руины великих залов, по которым когда-то ходили великаны) и вы научились постоять за себя во время их исследования. Время от времени вы служили проводником дружелюбным служителям природы, которые были достаточно любезны, чтобы научить вас основам использования магии дикой природы.','Выберите А или Б: А) Короткий лук, 20 стрел, инструменты картографа, спальник, колчан, палатка, одежда путешественника, 3 зм; Б) 50 зм.','Инструменты картографа', (SELECT id FROM feat WHERE code = 'Magic_Initiate')),
('Artisan', 'Ремесленник', 'Вы начали мыть полы и драить прилавки в мастерской ремесленника за несколько медяков в день, как только стали достаточно сильным, чтобы нести ведро. Когда вы, наконец, стали достаточно взрослым, чтобы стать учеником, вы научились создавать свои собственные простые поделки, а также научились умасливать требовательных клиентов. Ваша профессия также привила вам чуткость к деталям.','Выберите А или Б: А) Инструменты ремесленника (выбранный вами выше), 2 сумки, одежда путешественника, 32 зм; Б) 50 зм.','1 из инструментов ремесленника на ваш выбор', (SELECT id FROM feat WHERE code = 'Crafter')),
('Soldier', 'Солдат', 'Вы начали обучаться сражению в таком раннем возрасте, что у вас осталось лишь несколько драгоценных воспоминаний о том, какой была жизнь до того, как вы взяли в руки оружие. Битва у вас в крови. Иногда вы ловите себя на том, что рефлекторно выполняете основные боевые упражнения, которым научились в юности. В конце концов, вы применяете это обучение на поле боя, защищая королевство, ведя войну.','Выберите А или Б: А) Копьё, короткий лук, 20 стрел, игровой набор (выбранный выше), комплект целителя, колчан, одежда путешественника, 14 зм; Б) 50 зм.','1 игровой набор на ваш выбор', (SELECT id FROM feat WHERE code = 'Savage_Attacker')),
('Guard', 'Стражник', 'Ваши ноги начинают ныть, когда вы вспоминаете бесчисленные часы, которые вы провели на своём посту в башне. Вас учили смотреть одним глазом за стену, высматривая мародёров, выныривающих из близлежащего леса, а другим глазом в город, выискивая карманников и нарушителей спокойствия.','Выберите А или Б: А) Копьё, лёгкий арбалет, 20 болтов, игровой набор (тот, что был выбран выше), закрытый фонарь, кандалы, колчан, одежда путешественника, 12 зм; Б) 50 зм.','1 игровой набор на ваш выбор', (SELECT id FROM feat WHERE code = 'Alert')),
('Wayfarer', 'Странник', 'Вы выросли на улицах, в окружении таких же отбросов на обочине жизни, некоторые из которых были друзьями, другие - соперниками. Вы спали, где могли, и выполняли случайную работу за еду. Временами, когда голод становился невыносимым, вы прибегали к воровству. Тем не менее, вы никогда не теряли своей гордости и никогда не оставляли надежды. Судьба ещё не закончила с вами.','Выберите А или Б: А) 2 кинжала, воровские инструменты, игровой набор (любой), спальник, 2 сумки, одежда путешественника, 16 зм; Б) 50 зм','Воровские инструменты', (SELECT id FROM feat WHERE code = 'Lucky')),
('Merchant', 'Торговец', 'Вы были подмастерьем у погонщика караванов или лавочника, изучая основы торговли. Вы много путешествовали и зарабатывали на жизнь, покупая и продавая сырьё, необходимое ремесленникам для занятий своей работой, или готовые работы таких ремесленников. Вы могли перевозить товары из одного места в другое (на корабле, в повозке или караваном) или покупать их у странствующих торговцев и продавать в своей собственной лавке.','Выберите А или Б: А) Инструменты навигатора, 2 сумки, одежда путешественника, 22 зм; Б) 50 зм.','Инструменты навигатора', (SELECT id FROM feat WHERE code = 'Lucky')),
('Farmer', 'Фермер', 'Вы выросли близко к земле. Годы ухода за животными и возделывания земли наградили вас терпением и крепким здоровьем. Вы высоко цените щедрость природы и уважаете её гнев.','Выберите А или Б: А) Серп, инструменты плотника, комплект целителя, железный горшок, лопата, одежда путешественника, 30 зм, или Б) 50 зм.','Инструменты плотника', (SELECT id FROM feat WHERE code = 'Tough')),
('Charlatan', 'Шарлатан', 'С тех пор как вы достигли возраста, чтобы вам продали эль, у вас уже была любимая табуретка в каждой таверне в пределах 10 миль от того места, где вы родились. Путешествуя от одного питейного заведения к другому, вы научились наживаться на несчастных, которые искали утешительную ложь. Возможно, вы торговец поддельными зельями или строите из себя дворянина, используя поддельную родословную.','Выберите А или Б: А) Набор для фальсификации, костюм, парадная одежда, 15 зм; Б) 50 зм.','Набор для фальсификации', (SELECT id FROM feat WHERE code = 'Skilled'));

-- changeset ramoni73:V3__background_data_background_ability
INSERT INTO background_ability(background_id, ability_id) VALUES
((SELECT id FROM background WHERE code = 'Entertainer'), (SELECT id FROM ability WHERE code = 'STR')),
((SELECT id FROM background WHERE code = 'Entertainer'), (SELECT id FROM ability WHERE code = 'DEX')),
((SELECT id FROM background WHERE code = 'Entertainer'), (SELECT id FROM ability WHERE code = 'CHA')),
((SELECT id FROM background WHERE code = 'Noble'), (SELECT id FROM ability WHERE code = 'STR')),
((SELECT id FROM background WHERE code = 'Noble'), (SELECT id FROM ability WHERE code = 'INT')),
((SELECT id FROM background WHERE code = 'Noble'), (SELECT id FROM ability WHERE code = 'CHA')),
((SELECT id FROM background WHERE code = 'Sailor'), (SELECT id FROM ability WHERE code = 'STR')),
((SELECT id FROM background WHERE code = 'Sailor'), (SELECT id FROM ability WHERE code = 'DEX')),
((SELECT id FROM background WHERE code = 'Sailor'), (SELECT id FROM ability WHERE code = 'WIS')),
((SELECT id FROM background WHERE code = 'Sage'), (SELECT id FROM ability WHERE code = 'CON')),
((SELECT id FROM background WHERE code = 'Sage'), (SELECT id FROM ability WHERE code = 'INT')),
((SELECT id FROM background WHERE code = 'Sage'), (SELECT id FROM ability WHERE code = 'WIS')),
((SELECT id FROM background WHERE code = 'Hermit'), (SELECT id FROM ability WHERE code = 'CON')),
((SELECT id FROM background WHERE code = 'Hermit'), (SELECT id FROM ability WHERE code = 'WIS')),
((SELECT id FROM background WHERE code = 'Hermit'), (SELECT id FROM ability WHERE code = 'CHA')),
((SELECT id FROM background WHERE code = 'Scribe'), (SELECT id FROM ability WHERE code = 'DEX')),
((SELECT id FROM background WHERE code = 'Scribe'), (SELECT id FROM ability WHERE code = 'INT')),
((SELECT id FROM background WHERE code = 'Scribe'), (SELECT id FROM ability WHERE code = 'WIS')),
((SELECT id FROM background WHERE code = 'Acolyte'), (SELECT id FROM ability WHERE code = 'INT')),
((SELECT id FROM background WHERE code = 'Acolyte'), (SELECT id FROM ability WHERE code = 'WIS')),
((SELECT id FROM background WHERE code = 'Acolyte'), (SELECT id FROM ability WHERE code = 'CHA')),
((SELECT id FROM background WHERE code = 'Criminal'), (SELECT id FROM ability WHERE code = 'DEX')),
((SELECT id FROM background WHERE code = 'Criminal'), (SELECT id FROM ability WHERE code = 'CON')),
((SELECT id FROM background WHERE code = 'Criminal'), (SELECT id FROM ability WHERE code = 'INT')),
((SELECT id FROM background WHERE code = 'Guide'), (SELECT id FROM ability WHERE code = 'DEX')),
((SELECT id FROM background WHERE code = 'Guide'), (SELECT id FROM ability WHERE code = 'CON')),
((SELECT id FROM background WHERE code = 'Guide'), (SELECT id FROM ability WHERE code = 'WIS')),
((SELECT id FROM background WHERE code = 'Artisan'), (SELECT id FROM ability WHERE code = 'STR')),
((SELECT id FROM background WHERE code = 'Artisan'), (SELECT id FROM ability WHERE code = 'DEX')),
((SELECT id FROM background WHERE code = 'Artisan'), (SELECT id FROM ability WHERE code = 'INT')),
((SELECT id FROM background WHERE code = 'Soldier'), (SELECT id FROM ability WHERE code = 'STR')),
((SELECT id FROM background WHERE code = 'Soldier'), (SELECT id FROM ability WHERE code = 'DEX')),
((SELECT id FROM background WHERE code = 'Soldier'), (SELECT id FROM ability WHERE code = 'CON')),
((SELECT id FROM background WHERE code = 'Guard'), (SELECT id FROM ability WHERE code = 'STR')),
((SELECT id FROM background WHERE code = 'Guard'), (SELECT id FROM ability WHERE code = 'INT')),
((SELECT id FROM background WHERE code = 'Guard'), (SELECT id FROM ability WHERE code = 'WIS')),
((SELECT id FROM background WHERE code = 'Wayfarer'), (SELECT id FROM ability WHERE code = 'DEX')),
((SELECT id FROM background WHERE code = 'Wayfarer'), (SELECT id FROM ability WHERE code = 'WIS')),
((SELECT id FROM background WHERE code = 'Wayfarer'), (SELECT id FROM ability WHERE code = 'CHA')),
((SELECT id FROM background WHERE code = 'Merchant'), (SELECT id FROM ability WHERE code = 'CON')),
((SELECT id FROM background WHERE code = 'Merchant'), (SELECT id FROM ability WHERE code = 'INT')),
((SELECT id FROM background WHERE code = 'Merchant'), (SELECT id FROM ability WHERE code = 'CHA')),
((SELECT id FROM background WHERE code = 'Farmer'), (SELECT id FROM ability WHERE code = 'STR')),
((SELECT id FROM background WHERE code = 'Farmer'), (SELECT id FROM ability WHERE code = 'CON')),
((SELECT id FROM background WHERE code = 'Farmer'), (SELECT id FROM ability WHERE code = 'WIS')),
((SELECT id FROM background WHERE code = 'Charlatan'), (SELECT id FROM ability WHERE code = 'DEX')),
((SELECT id FROM background WHERE code = 'Charlatan'), (SELECT id FROM ability WHERE code = 'CON')),
((SELECT id FROM background WHERE code = 'Charlatan'), (SELECT id FROM ability WHERE code = 'CHA'));

-- changeset ramoni73:V3__background_data_background_skill
INSERT INTO background_skill(background_id, skill_id) VALUES
((SELECT id FROM background WHERE code = 'Entertainer'), (SELECT id FROM skill WHERE code = 'Acrobatics')),
((SELECT id FROM background WHERE code = 'Entertainer'), (SELECT id FROM skill WHERE code = 'Performance')),
((SELECT id FROM background WHERE code = 'Noble'), (SELECT id FROM skill WHERE code = 'History')),
((SELECT id FROM background WHERE code = 'Noble'), (SELECT id FROM skill WHERE code = 'Persuasion')),
((SELECT id FROM background WHERE code = 'Sailor'), (SELECT id FROM skill WHERE code = 'Acrobatics')),
((SELECT id FROM background WHERE code = 'Sailor'), (SELECT id FROM skill WHERE code = 'Perception')),
((SELECT id FROM background WHERE code = 'Sage'), (SELECT id FROM skill WHERE code = 'Arcana')),
((SELECT id FROM background WHERE code = 'Sage'), (SELECT id FROM skill WHERE code = 'History')),
((SELECT id FROM background WHERE code = 'Hermit'), (SELECT id FROM skill WHERE code = 'Medicine')),
((SELECT id FROM background WHERE code = 'Hermit'), (SELECT id FROM skill WHERE code = 'Religion')),
((SELECT id FROM background WHERE code = 'Scribe'), (SELECT id FROM skill WHERE code = 'Investigation')),
((SELECT id FROM background WHERE code = 'Scribe'), (SELECT id FROM skill WHERE code = 'Perception')),
((SELECT id FROM background WHERE code = 'Acolyte'), (SELECT id FROM skill WHERE code = 'Insight')),
((SELECT id FROM background WHERE code = 'Acolyte'), (SELECT id FROM skill WHERE code = 'Religion')),
((SELECT id FROM background WHERE code = 'Criminal'), (SELECT id FROM skill WHERE code = 'Sleight_of_Hand')),
((SELECT id FROM background WHERE code = 'Criminal'), (SELECT id FROM skill WHERE code = 'Stealth')),
((SELECT id FROM background WHERE code = 'Guide'), (SELECT id FROM skill WHERE code = 'Stealth')),
((SELECT id FROM background WHERE code = 'Guide'), (SELECT id FROM skill WHERE code = 'Survival')),
((SELECT id FROM background WHERE code = 'Artisan'), (SELECT id FROM skill WHERE code = 'Investigation')),
((SELECT id FROM background WHERE code = 'Artisan'), (SELECT id FROM skill WHERE code = 'Persuasion')),
((SELECT id FROM background WHERE code = 'Soldier'), (SELECT id FROM skill WHERE code = 'Athletics')),
((SELECT id FROM background WHERE code = 'Soldier'), (SELECT id FROM skill WHERE code = 'Intimidation')),
((SELECT id FROM background WHERE code = 'Guard'), (SELECT id FROM skill WHERE code = 'Athletics')),
((SELECT id FROM background WHERE code = 'Guard'), (SELECT id FROM skill WHERE code = 'Perception')),
((SELECT id FROM background WHERE code = 'Wayfarer'), (SELECT id FROM skill WHERE code = 'Insight')),
((SELECT id FROM background WHERE code = 'Wayfarer'), (SELECT id FROM skill WHERE code = 'Stealth')),
((SELECT id FROM background WHERE code = 'Merchant'), (SELECT id FROM skill WHERE code = 'Animal_Handling')),
((SELECT id FROM background WHERE code = 'Merchant'), (SELECT id FROM skill WHERE code = 'Persuasion')),
((SELECT id FROM background WHERE code = 'Farmer'), (SELECT id FROM skill WHERE code = 'Animal_Handling')),
((SELECT id FROM background WHERE code = 'Farmer'), (SELECT id FROM skill WHERE code = 'Nature')),
((SELECT id FROM background WHERE code = 'Charlatan'), (SELECT id FROM skill WHERE code = 'Deception')),
((SELECT id FROM background WHERE code = 'Charlatan'), (SELECT id FROM skill WHERE code = 'Sleight_of_Hand'));
