spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/character_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml