server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: character-service
  data:
    mongodb:
      uri: mongodb://${CHARACTER_DB_USER:character_user}:${CHARACTER_DB_PASSWORD:character_password}@localhost:27017/${CHARACTER_DB_NAME:character_db}
