-- liquibase formatted sql

-- changeset ramoni73:basic_data_feat
INSERT INTO feat (code, name, category) VALUES
('Alert', 'Бдительный', 'ORIGIN'),
('Lucky', 'Везунчик', 'ORIGIN'),
('Savage_Attacker', 'Дикий атакующий', 'ORIGIN'),
('Tavern_Brawler', 'Драчун', 'ORIGIN'),
('Tough', 'Крепкий', 'ORIGIN'),
('Healer', 'Лекарь', 'ORIGIN'),
('Musician', 'Музыкант', 'ORIGIN'),
('Skilled', 'Одарённый', 'ORIGIN'),
('Magic_Initiate', 'Посвящённый в магию', 'ORIGIN'),
('Crafter', 'Ремесленник', 'ORIGIN'),
('Elemental_Adept', 'Адепт стихий', 'GENERAL'),
('Actor', 'Актёр', 'GENERAL'),
('Athlete', 'Атлет', 'GENERAL'),
('War_Caster', 'Боевой заклинатель', 'GENERAL'),
('Grappler', 'Борец', 'GENERAL'),
('Martial_Weapon_Training', 'Владение воинским оружием', 'GENERAL'),
('Inspiring_Leader', 'Воодушевляющий лидер', 'GENERAL'),
('Shadow_Touched', 'Затронутый тенью', 'GENERAL'),
('Fey_Touched', 'Затронутый феями', 'GENERAL'),
('Lightly_Armored', 'Знаток лёгких доспехов', 'GENERAL'),
('Moderately_Armored', 'Знаток средних доспехов', 'GENERAL'),
('Heavily_Armored', 'Знаток тяжёлых доспехов', 'GENERAL'),
('Dual_Wielder', 'Использование двух оружий', 'GENERAL'),
('Crusher', 'Крушитель', 'GENERAL'),
('Great_Weapon_Master', 'Мастер большого оружия', 'GENERAL'),
('Polearm_Master', 'Мастер древкового оружия', 'GENERAL'),
('Weapon_Master', 'Мастер оружия', 'GENERAL'),
('Medium_Armor_Master', 'Мастер средних доспехов', 'GENERAL'),
('Heavy_Armor_Master', 'Мастер тяжёлых доспехов', 'GENERAL'),
('Shield_Master', 'Мастер щитов', 'GENERAL'),
('Spell_Sniper', 'Меткий заклинатель', 'GENERAL'),
('Sharpshooter', 'Меткий стрелок', 'GENERAL'),
('Observant', 'Наблюдательный', 'GENERAL'),
('Charger', 'Налётчик', 'GENERAL'),
('Defensive_Duelist', 'Оборонительный дуэлянт', 'GENERAL'),
('Keen_Mind', 'Острый ум', 'GENERAL'),
('Poisoner', 'Отравитель', 'GENERAL'),
('Speedy', 'Подвижный', 'GENERAL'),
('Piercer', 'Пронзатель', 'GENERAL'),
('Skulker', 'Проныра', 'GENERAL'),
('Ritual_Caster', 'Ритуальный заклинатель', 'GENERAL'),
('Slasher', 'Рубака', 'GENERAL'),
('Durable', 'Стойкий', 'GENERAL'),
('Sentinel', 'Страж', 'GENERAL'),
('Telekinetic', 'Телекинетик', 'GENERAL'),
('Telepathic', 'Телепат', 'GENERAL'),
('Mage_Slayer', 'Убийца магов', 'GENERAL'),
('Ability_Score_Improvement', 'Улучшение характеристик', 'GENERAL'),
('Resilient', 'Устойчивый', 'GENERAL'),
('Chef', 'Шеф-повар', 'GENERAL'),
('Crossbow_Expert', 'Эксперт в арбалетах', 'GENERAL'),
('Skill_Expert', 'Эксперт в навыке', 'GENERAL'),
('Dueling', 'Дуэлянт', 'FIGHTING_STYLE'),
('Protection', 'Защита', 'FIGHTING_STYLE'),
('Defense', 'Оборона', 'FIGHTING_STYLE'),
('Interception', 'Перехват', 'FIGHTING_STYLE'),
('Great_Weapon_Fighting', 'Сражение большим оружием', 'FIGHTING_STYLE'),
('Blind_Fighting', 'Сражение вслепую', 'FIGHTING_STYLE'),
('Unarmed_Fighting', 'Сражение голыми руками', 'FIGHTING_STYLE'),
('Two_Weapon_Fighting', 'Сражение двумя оружиями', 'FIGHTING_STYLE'),
('Thrown_Weapon_Fighting', 'Сражение метательным оружием', 'FIGHTING_STYLE'),
('Archery', 'Стрельба из лука', 'FIGHTING_STYLE'),
('Boon_of_Combat_Prowess', 'Дар боевой доблести', 'EPIC_BOON'),
('Boon_of_Recovery', 'Дар восстановления', 'EPIC_BOON'),
('Boon_of_Spell_Recall', 'Дар восстановления чар', 'EPIC_BOON'),
('Boon_of_the_Night_Spirit', 'Дар духа ночи', 'EPIC_BOON'),
('Boon_of_Truesight', 'Дар истинного зрения', 'EPIC_BOON'),
('Boon_of_Irresistible_Offense', 'Дар непреодолимого нападения', 'EPIC_BOON'),
('Boon_of_Dimensional_Travel', 'Дар пространственного путешествия', 'EPIC_BOON'),
('Boon_of_Speed', 'Дар скорости', 'EPIC_BOON'),
('Boon_of_Fortitude', 'Дар стойкости', 'EPIC_BOON'),
('Boon_of_Fate', 'Дар судьбы', 'EPIC_BOON'),
('Boon_of_Energy_Resistance', 'Дар устойчивости к энергиям', 'EPIC_BOON');