apiVersion: v1
kind: Service
metadata:
  name: dice-service
spec:
  selector:
    app: dice-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP # Для доступа внутри кластера